version: '3.8'

volumes:
  data:
  letsencrypt:
  tailscale:
  
services:
  nginx-proxy-manager:
    depends_on:
      - tailscale
    network_mode: host
    container_name: nginx-proxy-manager
    # user: '1000:1000'
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    environment:
      - TZ=Africa/Tunis
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
  tailscale:
    restart: unless-stopped
    container_name: nginx_tailscale
    hostname: n0t3x1l-nginx
    image: tailscale/tailscale:latest
    volumes:
      - tailscale:/var/lib
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    command: tailscaled