version: "3"
services:
  watchtower:
    restart: unless-stopped
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 20 * * 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock