name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at every 12AM UTC
    - cron: "0 0 * * *"

jobs:
  generate_wakatime_readme:
    runs-on: ubuntu-latest
    steps:
      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          filename: profile/charts/metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          base: ""
          formats: json
          plugin_wakatime: yes
          plugin_wakatime_sections: languages-graphs
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
